
var script = [
	{
		"id":1,
		"background":"카라잔",
		"image1":"메디브",
		"image2":"",
		"image3":"",
		"bgm":"카라잔",
		"name":"대마법사 메디브",
		"text":"나, 대마법사 메디브가 아제로스 제일의 파티에 그대를 초대하네!",
		"next":"",
		"select":""
	}, 
	{
		"id":2,
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"대마법사 메디브",
		"text":"어서 와~ 모두 널 기다려!",
		"next":"",
		"select":""
	}, 
	{
		"id":3,
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"대마법사 메디브",
		"text":"놀라운 맛(맛!) 만찬을 즐기며",
		"next":"",
		"select":""
	}, 
	{
		"id":4,
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"대마법사 메디브",
		"text":"다 함께 몸을 흔들어봐!",
		"next":"",
		"select":""
	}, 
	{
		"id":5,
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"대마법사 메디브",
		"text":"커다란 체스(체스!) 반칙은 금지야",
		"next":"",
		"select":""
	}, 
	{
		"id":6,
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"대마법사 메디브",
		"text":"오늘 밤 걱정은 전부 떨쳐버리고",
		"next":"",
		"select":""
	}, 
	{
		"id":7,
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"대마법사 메디브",
		"text":"빠져봐~ 모든 걸 잊고~",
		"next":"",
		"select":""
	}, 
	{
		"id":8,
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"대마법사 메디브",
		"text":"여기가 바로 네가 꿈꾸던 그 파라다이스",
		"next":"",
		"select":""
	}, 
	{
		"id":9,
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"대마법사 메디브",
		"text":"황홀한 이곳(황홀해!) 한여름 밤의 카라잔!",
		"next":"",
		"select":""
	}, 
	{
		"id":10,
		"background":"none",
		"image1":"none",
		"image2":"",
		"image3":"",
		"bgm":"대기",
		"name":"",
		"text":"",
		"next":"",
		"select":""
	}, 
	{
		"id":11,
		"background":"",
		"image1":"모로스",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"모로스",
		"text":"다시 보시겠습니까?",
		"next":"",
		"select":"예:a,아니요:b"
	}, 
	{
		"id":"a",
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"모로스",
		"text":"네, 그럼 다시 들어보시겠습니다.",
		"next":1,
		"select":""
	}, 
	{
		"id":"b",
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"모로스",
		"text":"모두 수고하셨습니다.",
		"next":"",
		"select":"이의있소:c,잠깐!:c,받아라!:c,이겼다!:c"
	}, 
	{
		"id":"c",
		"background":"",
		"image1":"",
		"image2":"",
		"image3":"",
		"bgm":"",
		"name":"모로스",
		"text":"다음에 봐요~",
		"next":"end",
		"select":""
	}
];
